apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: kpi7bo2qj-nodejs 
  janus-idp.io/tekton: kpi7bo2qj-nodejs
  backstage.io/kubernetes-id: kpi7bo2qj-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: kpi7bo2qj-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml