apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kpi7bo2qj-nodejs
  janus-idp.io/tekton: kpi7bo2qj-nodejs
  backstage.io/kubernetes-id: kpi7bo2qj-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: kpi7bo2qj-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
