apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: kpi7bo2qj-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kpi7bo2qj-nodejs 
  name: kpi7bo2qj-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: kpi7bo2qj-nodejs 
